### DISCUSSION TITLE
How to use dark mode on non-quasar components?

### DISCUSSION THREAD

**Discussion by wsw70** [quasarframework/quasar#10189] [General - Components / Directives / etc] [answered]
I would like to be able to switch my app to dark mode at night. I read the [docs ](https://quasar.dev/style/dark-mode) and successfully switched the modes.

I am now trying to understand how to use this feature in practice. Below is a part of my app in day and night mode:

![image](https://user-images.githubusercontent.com/1345886/126908790-cbad29d3-e785-4fd7-80fb-135945781d56.png)

![image](https://user-images.githubusercontent.com/1345886/126908792-7c3be95e-b1d6-4919-8cff-0b1cad3709c6.png)

The top line is fine, the background switched to black and the font to white automatically

In the second row, the background was set by me via standard styling (`background-color`) and it was not (miraculously) changed. 

How should I tell Quasar "if you have color A in light mode, switch it to color B in dark mode" (applicable globally), or "here is `background-color` for dark mode"?

**Comment by MilosPaunovic** [comment]
You can check which mode is active and bind classes (or change component props such as colors) accordingly.
Check [this](https://quasar.dev/quasar-plugins/dark#inside-of-a-vue-file) page of the official docs.

**Reply by wsw70** [reply]
Thank you. So if I understand correctly, there is no way to do a global mapping of colors, and use `color-one` that would be mapped to a specific one depending on the current mode?

Otherwise it means that I have to use dynamic classes for each and every component (which is doable, just less practical)

**Comment by hawkeye64** [comment, marked as answer]
@wsw70 If you know the css, you can add your own that switches automatically for quasar dark mode:

```css
.q-dark div,
.body--dark div

  &.weather-app-css
    background: #d1d1d1
    color: #fefefe
```
Just change the name of `.weather-app-css` and this may be needed for deep nested css as well.

**Reply by wsw70** [reply]
@hawkeye64 I added the styling to the component as

```css
<style scoped lang="scss">

.q-dark div,
.body--dark div {
  &.calendar {
     color: #fefefe;
    background-color: black;
   }
}


.calendar {
  display: grid;
  grid-template-columns: [hour] 130px [event] auto;
  column-gap: 10px;
  row-gap: 5px;
}

(...)
```

and it almost worked:

![image](https://user-images.githubusercontent.com/1345886/127011209-a6aed759-6eba-490f-8f0a-73af17189946.png)

I believe the green parts correspond to CSS grid gaps of the parent element which seem not to be possible to style. I will have to rethink how I manage the components to make it work.
