### DISCUSSION TITLE
q-separator with left closing and right opening

### DISCUSSION THREAD

**Discussion by tianhuat** [quasarframework/quasar#11336] [General - Components / Directives / etc]
From the example here:
https://quasar.dev/vue-components/separator#usage
You can see that using `<q-separator inset="item" />` we can get separator with left opening and right closing (it's the original separator in the attached image)
Is there away to do the opposite (left closing and right opening) as highlighted in the red line below? 
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/aBdOK.png

**Comment by MilosPaunovic** [comment]
[https://codepen.io/milospaunovic/pen/yLoRmZv](https://codepen.io/milospaunovic/pen/yLoRmZv)

```css
.q-separator--horizontal-item-inset {
    margin-left: 0px;
    margin-right: 72px;
}
```
