### DISCUSSION TITLE
SassError: Undefined variable when using Quasar variables outside Vue SFC

### DISCUSSION THREAD

**Discussion by lucasdavidferrero** [quasarframework/quasar#12128] [General - Components / Directives / etc] [answered]
I've a problem compiling sass when using Quasar variables in .scss files.
This project requires isolating styles in  a separate file (.scss) instead of writing those styles in <style> block.

This is how the folder structure for "Pedidos" feature looks like:
_src/components/Pedidos_
![2022-01-20_16h05_38](https://user-images.githubusercontent.com/15804058/150405656-2461dc75-7462-4593-8e94-b33a3259e090.png)

The SCSS code
*src/components/Pedidos/_PedidoItem.scss*
```scss
.pedido-item {
  border: 1px solid rgba(black, 20%);
  border-radius: $generic-border-radius; // Sass compiler throws -> SassError: Undefined variable
  background: red;
}
.pedido-item-body {
  padding: 0.5rem;
  @media (min-width: $breakpoint-md-min) {
    flex-grow: 1;
    display: flex;
    justify-content: space-between;
  }
}
```

Finally, the component that uses the above styles:
*src/components/Pedidos/PedidoItem.vue*
```vue
...
<style lang="scss">
  @import "./PedidoItem.scss";
</style>
```
This is the error that webpack throws:
```console
[webpack-dev-server] ERROR in ./src/components/webpage/Pedidos/PedidoItem.vue?vue&type=style&index=0&id=0ffc2055&lang=scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-18.use[1]!./node_modules/vue-loader/dist/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-18.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-18.use[3]!./node_modules/@quasar/app/lib/webpack/loader.quasar-scss-variables.js!./node_modules/@quasar/app/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/components/webpage/Pedidos/PedidoItem.vue?vue&type=style&index=0&id=0ffc2055&lang=scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
3 │   border-radius: $generic-border-radius;
  │                  ^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\components\webpage\Pedidos\_PedidoItem.scss 3:18  @import
  src\components\webpage\Pedidos\PedidoItem.vue 2:9     root stylesheet
```
If I write those styles directly in <style> block, It works perfectly fine.

My question: How can I use Quasar variables in a .scss file and use that file inside <style> block?
