### DISCUSSION TITLE
How to remove q-focus-helper and other hover propeties from q-btn?

### DISCUSSION THREAD

**Discussion by chevyweird** [quasarframework/quasar#12542] [General - Components / Directives / etc] [answered]
I’m creating my own style for q-btn and there’s this overlay on hover that keeps bugging me.
I’ve examined the css and its the class .q-focus-helper that does it.
For the life of me, I cannot find a way to override that class or how to disable it.

Anybody can help with that?

**Comment by MilosPaunovic** [comment, marked as answer]
```css
.q-hoverable:hover > .q-focus-helper {
  opacity: 0 !important;
}
```

[https://codepen.io/milospaunovic/pen/VwrXrZE?editors=1100](https://codepen.io/milospaunovic/pen/VwrXrZE?editors=1100)
