### DISCUSSION TITLE
Can I disable pointer events on a q-scroll-area but still allow it to scroll?

### DISCUSSION THREAD

**Discussion by RebeccaStevens** [quasarframework/quasar#13391] [General - Components / Directives / etc] [answered]
Essentially what I want to do is have a `q-scroll-area` (inside a `q-drawer`) with a transparent background that will ignore pointer events unless those pointer events are on a child element.
So the children will still be interactable but the background won't be.

I tried essentially the following:

```css
.q-drawer {
  background-color: transparent;
  pointer-events: none;
}

.q-drawer > * {
  pointer-events: all;
}
```

This mostly worked but scrolling of the `q-scroll-area` was no longer possible.

Anyone have any idea on how I can resolve this?

[codepen](https://codepen.io/rebeccastevens-the-decoder/pen/BaYzJzw)
