### DISCUSSION TITLE
q-select: Add a prop to reduce the height when the label is not displayed

### DISCUSSION THREAD

**Discussion by zeodtr** [quasarframework/quasar#13411] [Ideas / Proposals]
I want to reduce the height of q-select.  
I've removed the label by setting `label` prop to `undefined`, but q-select's height remains the same.  
Even with `dense` prop set to true, it is too tall for me (The result height is 40px).
I've managed to reduce the height of q-select by applying the following scss. But I think it is a hack, since it uses the undocumented css classes.

```scss
$height: 30px;
:deep(.q-field__control) {
    min-height: $height !important;
    height: auto !important;
    padding-right: 4px !important;
    .q-field__native {
        min-height: $height !important;
        height: auto !important;
    }
    .q-field__append {
        min-height: $height !important;
        height: auto !important;
    }
}
```

It would be nice if the height could be reduced by a prop.

BTW, I've looked at the source code of quasar, and found that the height is kind of hard-coded.  
https://github.com/quasarframework/quasar/blob/dev/ui/src/components/field/QField.sass

Thanks.
