### DISCUSSION TITLE
Label problem at border top / outlined

### DISCUSSION THREAD

**Discussion by rodolfoserralha** [quasarframework/quasar#13587] [General - Components / Directives / etc]
Hi guys, I'm sorry to ask that question, I think that is something really easy to do but I couldn't find the problem. My label is bugged and It don't move to the top of the line in input. 

I'm getting this result instead of the correct one in codepen

![Captura de tela 2022-06-01 190226](https://user-images.githubusercontent.com/87541163/171509366-4f88b50e-a38e-4619-83b9-d3a3013d7691.png)

I'm trying to copy a input by this link https://codepen.io/smolinari/pen/abvwQzR but the label don't work on my project. 

`			<q-input
				class="my-input"
				outlined
				v-model="text"
				label="Label"
				:dense="dense"
			></q-input>`

This is the input i'm copying

**Comment by MilosPaunovic** [comment]
Copy the CSS part from the Codepen, as well:
[https://codepen.io/smolinari/pen/abvwQzR](https://codepen.io/smolinari/pen/abvwQzR)

```css
.required .q-field__label:before {
  content: '* ';
  color: #f00;
}

.my-input.q-field--float .q-field__label {
  transform: translateY(-120%) translateX(-5px) scale(0.75);
  background: #fff;
  right: inherit;
  padding: 0 5px;
  z-index: 10;
}

.my-input.q-field--dense.q-field--float .q-field__label {
    transform: translateY(-85%) translateX(-5px) scale(0.75);
}

.my-input.q-field--labeled .q-field__native,
.my-input.q-field--labeled .q-field__prefix,
.my-input.q-field--labeled .q-field__suffix {
  padding-top: 8px;
}
```
