### DISCUSSION TITLE
Error command 'dev' not working

### DISCUSSION THREAD

**Discussion by Jasminahmad** [quasarframework/quasar#13675] [General - Components / Directives / etc] [answered]
I have a problem in launching Quasar projects that I didn't create. I want to open a quasar project that I have cloned from Gittea and I used "npx quasar dev" and it doesnt work. If I create the project, it will work. Is there any other commands to launch the project that haven't been created by me?

**Comment by suleimanas** [comment]
whats the error message/s?
which version is it?
did you npm install the project's packages?

**Reply by Jasminahmad** [reply]
The error said, Error unknown command "dev"
My quasar version has been upgraded to 3.3.3
How do I know whether npm has installed the project's packages?
<img width="437" alt="Screenshot 2022-06-13 at 11 56 59 AM" src="https://user-images.githubusercontent.com/76095479/173277112-5a8548f3-1926-4d61-97c9-dd8043b569c9.png">

**Reply by Jasminahmad** [reply]
This was in package.json file. I am not sure if there is anything else that must be added. I even compared to the another project's package.json file that I have created and I seem to not know what's the problem.


{
  "name": "ticket-system",
  "version": "0.0.1",
  "description": "Ticketing system",
  "productName": "Ticket System",
  "author": "Jasmin",
  "private": true,
  "scripts": {
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "quasar": "^2.6.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0"
  },
  "devDependencies": {
    "@quasar/app-vite": "^1.0.0",
    "autoprefixer": "^10.4.2"
  },
  "engines": {
    "node": "^18 || ^16 || ^14.19",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}

**Comment by suleimanas** [comment, marked as answer]
did you run: (npm install) ?

**Reply by Jasminahmad** [reply]
I just did and I was told to install to the latest version and I finally can open it! Thank you for helping!

**Reply by suleimanas** [reply]
remember (npx quasar ...) only helps you run quasar commands without the need to install @quasar/cli globally but you still need to install your local packages.

**Reply by Jasminahmad** [reply]
Alright noted. Thank you so much. Really appreciate your help!

**Comment by mcasto** [comment]
Okay ... I normally use a Mac. I developed an Electron app on my Mac and want to build it for Win. I pulled out my rarely-used Windows laptop and installed Quasar with "npm i -g @quasar/cli"

I get the "unknown command 'dev'" error.

I first got it when I tried to run my Electron app, but I also get it when, from the command line, I type: "quasar dev -h"

Same for quasar build -h ... I get: Error  Unknown command "build"

It's a completely fresh install of quasar.

Here's the output of my quasar info (which works fine):


Operating System   	Windows_NT(10.0.22621) - win32/x64
NodeJs             	18.17.1

Global packages    	
  NPM              	10.1.0
  yarn             	1.22.19
  @quasar/cli      	2.2.3
  @quasar/icongenie	Not installed
  cordova          	Not installed

Networking         	
  Host             	mcasto
  Wi-Fi            	192.168.0.113

**Reply by shershen08** [reply]
+1 having same issue on mac

**Comment by disarticulate** [comment]
same issue, ran npm install, am inside vscodium linuxserver.io which runs a vm. 

quasar info:
```
Operating System        Linux(6.8.0-53-generic) - linux/x64
NodeJs                  22.14.0

Global packages    
  NPM                   10.9.2
  yarn                  Not installed
  pnpm                  Not installed
  bun                   Not installed
  @quasar/cli           2.4.1
  @quasar/icongenie     Not installed
  cordova               Not installed

Networking         
  Host                  028d90ae4e9e
  eth0                  172.20.0.2
```
```
---
#docker-compose.yaml
services:
  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: vscodium
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - CUSTOM_USER=test
      - PASSWORD=test
      - PUID=1000
      - PGID=1000
      - TZ=Chicago/America
      - SUBFOLDER=/vscode/
      - INSTALL_PACKAGES=nodejs|git|npm
    volumes:
      - ./config:/config
      - /home/app:/home/app
      - ./init.d:/custom-cont-init.d:ro
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
```
these containers can run a script to prep the dev space:
```
#!/bin/bash

#0_init.sh

#apt install -y npm nodejs git
npm config set prefix '~/.npm-global'
npm install -g @quasar/cli

export PATH="$(~/.npm-global/bin):$PATH"


curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

export NVM_DIR="$HOME/.nvm"

nvm install 20

nvm alias default 20

nvm use 20
```
