### DISCUSSION TITLE
my quasar docker

### DISCUSSION THREAD

**Discussion by leostereo** [quasarframework/quasar#13684] [CLI - PWA mode]
Hi guys , 
Just wanted to share my dockerfile and docker-compose to easy deploy my quasar proyects , 
any feedback about it would be wellcome, take a look here:

https://github.com/leostereo/quasar_docker

bye

**Comment by metalsadman** [comment]
the link is pointing somewhere else btw.

**Reply by leostereo** [reply]
thanks ... should be fixed

**Comment by suleimanas** [comment]
the only thing i would change is in Dockerfile, you should define the node version.
you don't want it to download and install the latest version on every build

**Reply by leostereo** [reply]
Good point , What do you think using node:lts-alpine ?  
Other:
HMR is not working properly when creating an app with vite.
Perhaps it needs more RAM , I created a  very cheap 2GB VM on virtualbox.
I will continue testing.

**Comment by TobyMosque** [comment]
here my dockerfile:

```dockerfile
FROM node:lts-alpine as global-deps-stage
RUN npm i -g @quasar/cli@latest

FROM global-deps-stage as develop-stage
WORKDIR /src
COPY package.json ./
COPY yarn.lock ./
COPY . .

FROM develop-stage as local-deps-stage
RUN yarn

FROM local-deps-stage as build-ssr-stage
RUN quasar build -m ssr

FROM local-deps-stage as build-pwa-stage
RUN quasar build -m pwa

FROM node:lts-alpine as prod-ssr-stage
WORKDIR /app
COPY --from=build-ssr-stage /src/dist/ssr .
RUN yarn
EXPOSE 3000
CMD ["node", "index.js"]

FROM nginx:stable-alpine as prod-pwa-stage
WORKDIR /app
COPY --from=build-pwa-stage /src/dist/pwa /usr/share/nginx/html.
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

and here, my **docker-compose.yml**
```yml
services:
  my_service_name.app:
    image: ${DOCKER_REGISTRY-}my_service_name_app
    volumes:
      - ./app:/src # ./app is where the quasar app lies.
```
**docker-compose.build.yml**
```yml
services:
  my_service_name.app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: prod-ssr-stage

  # my_service_name.app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #     target: prod-pwa-stage
```
**docker-compose.dev.yml**
```yml
services:
  my_service_name.app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: develop-stage
    command: /bin/sh -c "yarn && quasar upgrade -i && quasar dev -m ssr"

  # my_service_name.app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #     target: develop-stage
  #  command: /bin/sh -c "yarn && quasar upgrade -i && quasar dev -m pwa"
```

my package.json scripts:
```js
"scripts": {
  "dev": "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d",
  "build": "docker-compose -f docker-compose.yml -f docker-compose.build.yml up -d"
}
```

Regarding the HMR, if u're in the windows, docker runs under the WSL, so if u source is inside a windows partition, the HMR will not capture the change in the files.

in this case, i recommend u to use the VSCode and install the Remote Pack, and don't forget to clone your repo inside a Linux partition (anywhere inside the `/home/user` folder)
https://code.visualstudio.com/docs/remote/remote-overview
