### DISCUSSION TITLE
slider disappears in :hover active component

### DISCUSSION THREAD

**Discussion by romkhram** [quasarframework/quasar#14336] [General - Components / Directives / etc] [answered]
if you put the slider in the active at :hover component, it disappears when moved
https://codepen.io/romkhram/pen/YzLyeoM
how fix this?
Thanks

**Comment by metalsadman** [comment, marked as answer]
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#user_action_pseudo-classes
```css
.hover {
  &-wrapper {
   ...
     &:hover, &:active{
      .hover-slider{
        visibility: visible;
      }
    }
```
https://codepen.io/metalsadman/pen/QWryKym
