### DISCUSSION TITLE
How to change QSelect border color?

### DISCUSSION THREAD

**Discussion by BenJackGill** [quasarframework/quasar#14826] [General - Components / Directives / etc] [answered]
On my page I have a QCard and a QSelect element.

It looks like this:

<img width="350" alt="Screenshot 2022-11-06 at 11 23 47 am" src="https://user-images.githubusercontent.com/2043257/200154135-c4bfaa8a-eb87-441f-92dc-30a5d111407f.png">

But the QSelect border is slightlty darker than the QCard. So now I want to make the QSelect border the same as the QCard border.

After inspecting the QSelect element I thought I could target it like this, but it has no effect:

```SCSS
<style scoped lang="scss">
.q-field--outlined .q-field__control::before {
  border: 1px solid $separator-color !important;
}
</style>
```

Can anyone please tell me how to change the border color of the QSelect element?
