### DISCUSSION TITLE
q-img and fit attribute, can I use CSS object-fit instead?

### DISCUSSION THREAD

**Discussion by tonjo** [quasarframework/quasar#14864] [General - Components / Directives / etc] [answered]
Hi, 
I am in the need of controlling the object-fit CSS property for images, but I do **not** want to use `q-img` fit attribute.
My need is changing the fit behaviour applying different CSS, not using a dynamic property in Vue.
It seems not possibile, object-fit CSS is ignored, `q-img` will apply the default `fit="cover"` mode when fit attribute is not specified.
Any hints?
Thanks

I took the suggestion, here is my codepen.
The 2 central columns shows how CSS is **not** considered in q-img without `fit` attribute or with `fit="none"`
I labelled each example: 
Q1, Q2, 
QA, QB, 
QNA, QNB.
A, B.

QB should be the same as Q2 and B.
QNA should be the same as Q1 and A.

https://codepen.io/tonjo/pen/ExRWNZY

**Comment by pdanpdan** [comment]
make a codepen

**Reply by tonjo** [reply]
Discussion edited, I added a codepen

**Comment by pdanpdan** [comment, marked as answer]
For QImg you need to target the read image
I put the final `.q-img__image--loaded` so that the rule does not change the placeholder image, but it's not mandatory.
The full chain of selectors is used so that you can put a QImg in another QImg

```css
.q-img.contain > .q-img__container > .q-img__image.q-img__image--loaded {
    object-fit: contain !important;
}

.q-img.cover > .q-img__container > .q-img__image.q-img__image--loaded {
    object-fit: cover !important;
}
```

https://codepen.io/pdanpdan/pen/GRGWvjR?editors=1100

(fixed wrong codepen link)
