### DISCUSSION TITLE
[Feature Request] Add dropdown-icon-color to QSelect API

### DISCUSSION THREAD

**Discussion by arnonrdp** [quasarframework/quasar#14923] [Ideas / Proposals]
I think would be good if we have a dropdown-icon-color added to QSelect API.

This way we can have this:
<img width="246" alt="dropdown" src="https://user-images.githubusercontent.com/26576201/202474185-a0f4d82f-99a1-4617-b902-91933e46598c.png">

Instead of add the CSS rule:
```css
.q-select__dropdown-icon {
  color: blue;
}
```
