### DISCUSSION TITLE
qinput validation error-message in qtooltip

### DISCUSSION THREAD

**Discussion by s-light** [quasarframework/quasar#15092] [General - Components / Directives / etc]
hello community,

i have a table with inputs -
and would like to use the [qinput validation](https://quasar.dev/vue-components/input#validation) mechanism for some of the inputs.
for a cleaner UI i would like to have the error messages as [qtooltip](https://quasar.dev/vue-components/tooltip) - 
only showing when focus or cursor is on the cell..
`hide-bottom-space` fixes the basic layout.

what is the easiest way to combine these two?
or is there a easy bunch of css to *extract* the message element?

open for all tips and ideas! ;-)

sunny greetings
stefan

**Comment by s-light** [comment]
just tried a quick and dirty hack with a bunch of css:
```css
table.q-table label.q-field.q-field--error div.q-field__inner div.q-field__bottom {
	display: none;
	position: absolute;
	top: -1.5em;
	padding: 0.5em 1em;
        border-radius: 1em;
        box-shadow: 0 0 2px black;
	background: hsl(0, 0%, 100%);
        /* use the default bg-color for .q-table__card */
}
table.q-table label.q-field.q-field--dark.q-field--error div.q-field__inner div.q-field__bottom {
	background: var(--q-dark-page);
}
table.q-table label.q-field.q-field--error.q-field--focused div.q-field__inner div.q-field__bottom,
table.q-table label.q-field.q-field--error:hover div.q-field__inner div.q-field__bottom {
	display: block;
}
```
for now it is *basically* working..
