### DISCUSSION TITLE
Carousel - how to move the arrows and dot indicators closer to border/edge

### DISCUSSION THREAD

**Discussion by buffalus** [quasarframework/quasar#15146] [General - Components / Directives / etc] [answered]
Hi,

Re: Carousel

I need help how to move the left/right arrows and dot indicators more closer to border/edge.

Is it possible to use CSS padding?

Thanks.
![carousel](https://user-images.githubusercontent.com/25363950/208434733-c9730a9a-9bf9-44e3-a769-132a5727e404.png)

**Comment by metalsadman** [comment, marked as answer]
add negative margins
```css
.q-carousel__prev-arrow{
  margin-left: -15px;
}
.q-carousel__next-arrow{
  margin-right: -15px;
}
```

**Reply by buffalus** [reply]
Thank you.
I use the following codes, put them in app.scss and get the result I want.
``` css
.q-carousel__prev-arrow {
  left: 0;
}

.q-carousel__next-arrow {
  right: 0;
}

.q-carousel__navigation {
  bottom: 0;
}
```

Thanks a lot.
