### DISCUSSION TITLE
Error "WebSocket connection failed" in Quasar with docker

### DISCUSSION THREAD

**Discussion by ameganix** [quasarframework/quasar#15769] [General - Components / Directives / etc]
Hello all. 
I transfer the application from pure Vue 3 to Quasar 2. My application runs through docker.
I did not change the configuration of the docker files. For test, I just installed Quasar 2 as written in the official documentation. All default settings. The installer only indicated to use Vite. From settings I changed only this in the file quasar.config.js:
```
devServer: {
    open: false,
    port: 8080,
},
```

Help solve the problem. An error appears in the browser console: "WebSocket connection to 'ws://localhost:8080/ws' failed". And the page in the browser is constantly reloading. If replace Vite with Webpack, the error repeats, but without reloading the page.

The error occurs only in docker. If I run Quasar without docker, then everything works correctly. If I proxy Quasar to local Nginx, then everything works correctly.

Below is the docker configuration. In this configuration, pure Vue works great. The problem arose only after installing Quasar.

Here is part of file docker-compose.yml:
```
services:
  traefik:
    image: traefik:2.4
    command:
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entryPoints.http.address=:80
    ports:
      - "80:80"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

  frontend:
    build:
      context: frontend/docker/development/nginx
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
      - traefik.http.routers.frontend.entryPoints=http
      - traefik.http.services.frontend.loadBalancer.server.port=80
      - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
      - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
      - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
      - traefik.http.routers.frontend.middlewares=frontend-redirect

  frontend-node:
    build:
      context: frontend/docker/development/node
    environment:
      SITE_DOMAIN: ${SITE_DOMAIN}
      SITE_NAME: ${SITE_NAME}
    volumes:
      - ./frontend:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn quasar dev"
    tty: true
```

Here is file nginx default.conf:
```
server {
    listen 80;
    charset utf-8;
    server_tokens off;

    resolver 127.0.0.11 ipv6=off;

    add_header X-Frame-Options "SAMEORIGIN";

    location /health {
        add_header Content-Type text/plain;
        return 200 'alive';
    }

    location /ws {
        set $upstream http://frontend-node:8080;
        proxy_set_header  Host $host;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection "Upgrade";
        proxy_pass        $upstream;
        proxy_redirect    off;
    }

    location /api {
        set $upstream http://api;
        rewrite ^/api/?(.*) /$1 break;
        proxy_set_header  Host $host;
        proxy_pass        $upstream;
        proxy_redirect    off;
    }

    location / {
        set $upstream http://frontend-node:8080;
        proxy_set_header  Host $host;
        proxy_pass        $upstream;
        proxy_redirect    off;
    }
}
```
