### DISCUSSION TITLE
Serverless SSR - how to select the correct handler

### DISCUSSION THREAD

**Discussion by tonyskulk** [quasarframework/quasar#15920] [CLI - SSR mode]
Hi, I have a quasar 2 ssr app. I want to use serverless and have already updated the src-ssr/server.js like in the documentation:

```
export const listen = ssrListen(async ({ app, port, isReady, ssrHandler }) => {
  if (process.env.DEV) {
    await isReady()
    return await app.listen(port, () => {
      // we're ready to serve clients
    })
  } else { // in production
    return { handler: serverless(ssrHandler) }
  }
})
```

After I built with _quasar build -m ssr_ everything is packed in the dist/ssr folder. I yarn installed there and then added a serverless.yml in the root folder of the quasar app like this:

```
service: frontend
provider:
  name: aws
  runtime: nodejs18.x
  # stage: dev
  region: eu-central-1

functions:
  app:
    handler: dist/ssr/index.handler
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

```

After running serverless deploy everything gets deployed to aws lambda, but in the logs I can see that the handler _dist/ssr/index.handler_ could not be found. The dist/ssr/index.js is minified and uglified, so it is very hard to read anything in there. 
What is the correct handler reference that I have to put in the serverless.yml or is my src-ssr/server.js configuration not correct?
