### DISCUSSION TITLE
can not pass buildConfig to capacitor build

### DISCUSSION THREAD

**Discussion by mostafashr** [quasarframework/quasar#15987] [CLI - Capacitor / Cordova modes]
I am migrating my app from Cordova to capacitor.
in Cordova, there is a build config file where I can specify my team and signing certificate and publish my app but there is not such an option in capacitor mode. 
when I run the "quasar build -m capacitor -T ios" the Cli will use scheme App and create and App.xcworkspace and don't find my certificates and team.
with Cordova I use this command:
quasar build -m cordova -T ios -- --release --device --buildConfig='../build.json' 
and I specify :
```yaml
          cat <<EOF > build.json
              {
                "ios": {
                  "release": {
                    "codeSignIdentity": "$identity",
                    "developmentTeam": "$team",
                    "packageType": "$package_type",
                    "provisioningProfile": "$profile_uuid",
                    "automaticProvisioning": true
                  }
                }
              }
          EOF
```
then the cicd pipeline work flawlessly and find my configuration and publish my app.
is there any  way to pass these configuration to capacitor?
the error is : 

/Users/builder/clone/src-capacitor/ios/App/App.xcodeproj: error: Signing for "App" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'App' from project 'App')
