### DISCUSSION TITLE
How to add red asterisk to q-input field

### DISCUSSION THREAD

**Discussion by cdecinkoKnight** [quasarframework/quasar#16118] [General - Components / Directives / etc] [answered]
I found info on the old Quasar but how do you properly add a required red asterisk to a q-input field in Quasar 2?
I'd like it just inside the input but would be ok for it prepended to the hint.

**Comment by metalsadman** [comment, marked as answer]
override the label class and add css `content: " *"`
https://codepen.io/metalsadman/pen/BaGvPEb

**Comment by fairking** [comment]
You can use a standard `required` attribute:
``` html
<q-input required />

<q-input :required="form.is_required" />

<q-select required />
```

``` css
.q-field__control-container > .q-field__native:required ~ .q-field__label:after {
    content: ' *';
    color: red;
}
```
