### DISCUSSION TITLE
When running an application with Quasar CLI (vite) via docker, a problem occurs

### DISCUSSION THREAD

**Discussion by illia-bel** [quasarframework/quasar#16188] [General - Components / Directives / etc]
Infinite loading of the <script type="module" src="/.quasar/client-entry.js"></script> file appears.
---
Maybe someone has experienced this problem and can help me out

**How to reproduce**
1. Initialize the quasar application via the command and select vite
`yarn create quasar`

2. Run the application using this file `docker-compose.yml`
```yml
version: '3.6'
services:
  app:
    image: node:18
    working_dir: /var/www/
    volumes:
      - './:/var/www/'
    ports:
      - 9000:9000
    command: bash -c "yarn dev"
```

3. Note that DevTools in the network tab asks for the file `/.quasar/client-entry.js`
<img width="1440" alt="screen-01" src="https://github.com/quasarframework/quasar/assets/60644182/64bc1318-a851-4386-b05b-335e410a031b">
