### DISCUSSION TITLE
q-input textarea autogrow minimal height

### DISCUSSION THREAD

**Discussion by darkopetreski** [quasarframework/quasar#16383] [General - Components / Directives / etc] [answered]
Is it possible to set minimal height for q-input textarea autogrow ? I have tried rows=10 and only works if autogrow is not set, for autogrow it shrinks to 1 row. How to set min height for the text area when autogrow is active ?

**Comment by darkopetreski** [comment, marked as answer]
I found a quick solution, just set css min-height

```css
textarea.q-field__native  {
  min-height: 200px;
}
```
