### DISCUSSION TITLE
Readonly QInput with no special style

### DISCUSSION THREAD

**Discussion by Techn1c4l** [quasarframework/quasar#16653] [General - Components / Directives / etc] [answered]
What's the best way to retain default style settings (border and etc.) for the QInput with readonly=true? When readonly set to true, it changes border to dashed and removes glow on focus.
I've created a custom Vue component and using nativeEl.setAttribute('readonly', 'true'), but not sure this is the most easy and elegant way. Maybe it's possible to achieve using CSS?

**Comment by metalsadman** [comment, marked as answer]
```css
.q-field{
  &.q-field--readonly {
      .q-field__control {
        &:before {
          border-bottom-style: solid;
        }
      }
    }
}
```
readonly/disabled aren't focusable, so probably inspect more on the CSS and override them.
