### DISCUSSION TITLE
Customize font color

### DISCUSSION THREAD

**Discussion by kingsley8524267** [quasarframework/quasar#17066] [General - Components / Directives / etc]
I have 2 theme(day/night) and How can I customize the font-color in SCSS variable?

**Comment by truexor** [comment]
you can use `@mixin theme` to achieve your requirement

```scss
$day-font-color: #333;
$night-font-color: #ccc;

$font-color: $day-font-color;

@mixin theme($theme) {
  @if $theme == day {
    $font-color: $day-font-color;
  } @else if $theme == night {
    $font-color: $night-font-color;
  } @else {
    @error "Unknown theme #{$theme}.";
  }
}

body {
  color: $font-color;
}

.theme-day {
  @include theme(day);
}

.theme-night {
  @include theme(night);
}
``` 

Then you can add a `btn` and add JS/TS to it as:

```js
btn.addEventListener('click', () => {
  themeContainer.classList.toggle('theme-day');
  themeContainer.classList.toggle('theme-night');
});
```
