### DISCUSSION TITLE
Make outline/border color of input fields configurable with a SCSS variable

### DISCUSSION THREAD

**Discussion by ivanjaros** [quasarframework/quasar#17878] [Ideas / Proposals] [answered]
The default outline is grey and I want to change it but I see no suitable variable for it in the list https://quasar.dev/style/sass-scss-variables

**Comment by yusufkandemir** [comment, marked as answer]
It's hardcoded
https://github.com/quasarframework/quasar/blob/29a342174bd6238aa22ef698897414ec5934cdf5/ui/src/components/field/QField.sass#L262-L269

So, you will have to use CSS to override it. Example:
```css
.my-input.q-field--outlined .q-field__control:before {
  border-color: var(--q-accent); /* use the accent color instead of that grey */
}
/* q-input class="my-input" outlined */
```
This was for the outlined design. You can adjust it to other designs as needed.

I am changing this to a feature request so that it can be configured through a variable in the future.
