### DISCUSSION TITLE
Size stepper icons

### DISCUSSION THREAD

**Discussion by gittrolo** [quasarframework/quasar#9101] [General - Components / Directives / etc] [answered]
how to change the size of the stepper icons?

**Comment by hawkeye64** [comment, marked as answer]
@gittrolo You'd have to override css
```css
.q-stepper__dot
  height: 42px !important
  width: 42px !important
  min-width: 42px !important
  font-size: 30px !important
```
as an example
  
![image](https://user-images.githubusercontent.com/10262924/116580816-f7dc3580-a8d0-11eb-9c21-eaa8dc93b94f.png)

**Comment by gittrolo** [comment]
Thanks a lot

**Comment by c-sosa** [comment]
A probably better solution without abusing **!important** would be this if using a <style scoped> </style> tag in the specific VUE component
```css
:deep(.q-stepper__dot) {
    height: 42px 
    width: 42px 
    min-width: 42px
    font-size: 30px 
 }
```
