### ISSUE TITLE
`Syntax Error: SassError` in Quasar devServer with Yarn workspace

### ISSUE THREAD

**Issue by anhzf** [quasarframework/quasar#10172]
**Describe the bug**
So I've created a new yarn workspace as a step in reproduce but what I've got is `COMPILATION ERROR`

**To Reproduce**
1. `yarn init`
2. `git init`
3. `git submodule add -n web [quasarProjectRepositoryUrl] packages/web`
> this is a new quasar project with windicss configured via webpack, you can check out here https://github.com/iamlazy-dev/app-web
4. add `workspaces` fields in package.json in root project with `["packages/*"]` and set `private` fields to true
5. `yarn install`
6. add script `yarn workspace [packageName]` named "web"
7. execute `yarn web quasar dev` to start the devServer

**Expected behavior**
COMPILATION ERROR is gone

**Screenshots**
![image](https://user-images.githubusercontent.com/36941633/126796571-f6ec0668-45f1-4a3e-b354-b82da69653d3.png)

**Platform (please complete the following information):**
Quasar Version: 2
@quasar/app Version: 3.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 14.17.0
NPM: 6.14.13
Yarn: 1.22.10
Browsers: -
iOS: -
Android: -
Electron: -

**Additional context**
monorepo with yarn workspaces, yarn without workspace its fine as well as npm

**Comment by hawkeye64** [comment]
Have you done any research on this or just want members of the team to do that for you? If you need faster service, the you should investigate a bit and let us know what you have found.

While I don't specifically think this is a Quasar issue, searching for sass, sass-loader, webpack, yarn workspace, etc and some sort of correlation would have helped A LOT.

I found these:
https://github.com/webpack-contrib/sass-loader/issues/820
https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020
https://gitmemory.com/issue/yarnpkg/yarn/4867/520995582

The best I could figure is when in a yarn workspace (which I use all the time without issue) that uses a git sub-module, you have to `yarn install --force` in order to build the sass node bindings properly for it to work.

**Comment by anhzf** [comment]
> Have you done any research on this or just want members of the team to do that for you? If you need faster service, the you should investigate a bit and let us know what you have found.

In advance, I apologize and thank you so much to the quasar community especially to @hawkeye64.
I'll try my best after this 😅, it's sound new to me
I just try ```yarn install --force``` but nothing different

**Comment by hawkeye64** [comment]
@anhzf 
This is what I am seeing in dist/quasar.sass

```css
.q-loading-bar
  position: fixed
  z-index: $z-max
  transition: transform .5s cubic-bezier(0,0,.2,1), opacity .5s
  background: $red
  &--top
    left: 0 #{"/* rtl:ignore */"}
    right: 0 #{"/* rtl:ignore */"}
    top: 0
    width: 100%
  &--bottom
    left: 0 #{"/* rtl:ignore */"}
    right: 0 #{"/* rtl:ignore */"}
    bottom: 0
    width: 100%
  &--right
    top: 0
    bottom: 0
    right: 0
    height: 100%
  &--left
    top: 0
    bottom: 0
    left: 0
    height: 100%
```

This `left: 0 #{"/* rtl:ignore */"}` is a special syntax that allows this line to be ignored when also compiled for RTL.
However, in your quasar.sass, it appears as if you have a space separating the `#` and `{`.
Can you confirm this or is that just how the output was created?
