### ISSUE TITLE
Weird RTL behavior on some components

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#10457]
Hello,
I wanted to test the RTL mode, and I noticed some weird behavior on some components.
for example the QBadge component, in RTL mode there is a conflicting CSS class application :
```css
[dir="rtl"] .q-badge--floating {
    left: -3px;
}
[dir="ltr"] .q-badge--floating {
    right: -3px;
}
```
which gives this result :
![screen](https://user-images.githubusercontent.com/12255492/130487952-30349163-71d8-434e-af69-cbb0c89d09f6.png)

quasar transforme the "right" property into "left" but to keep both.
(https://github.com/quasarframework/quasar/blob/dev/ui/src/components/badge/QBadge.sass)

Thank you very much for your tremendous work .

**Comment by pdanpdan** [comment]
Hello. I don't understand, do you have `dir="ltr"` set on any of the QBadge's parents?
How are you using Quasar? (cli, umd, vue cli)
How are you testing?

**Comment by RejDev** [comment]
Hello,
I use Quasar with CLI,

Quasar Build info :
```
 Dev mode.......... spa
 Pkg quasar........ v2.0.4
 Pkg @quasar/app... v3.1.0
 Pkg webpack....... v5
 Debugging......... enabled
```
 
 quasar.conf.js :
```
    build: {
       rtl: true,
       ...
```


here is a piece of code that shows the anomaly, when I activate the **dir = "rtl"**, QBadge is displayed as on the previous image, and when I analyze the generated code, I find that two css class conflicting are applied at the same time.

```CSS
[dir="rtl"] .q-badge--floating {
    left: -3px;
}
[dir="ltr"] .q-badge--floating {
    right: -3px;
}
```
right: -3px; of LTR  stay applied, whereas normally only the RTL should be active.
it's like I have a mixed of LTR + RTL

Code :
this happens when **dir="rtl"** is on the parent (q-btn)

```HTML
     <q-btn dir="rtl" flat push dense round color="transparent" icon="message" text-color="reverse-primary2" >
          <q-badge color="secondary" text-color="primary2" floating>2</q-badge>
          <q-menu transition-show="jump-down" transition-hide="jump-up">
            <messages-menu-component></messages-menu-component>
          </q-menu>
          <q-tooltip class="bg-primary2 text-reverse-primary2">Messages</q-tooltip>
     </q-btn>
```

thanks in advance..
