### ISSUE TITLE
[ios11] topbar no color bug

### ISSUE THREAD

**Issue by lenvonsam** [quasarframework/quasar#1116]
# Bug
when i cordova build ios(choose quasar ios theme mode), and run real iphone8, the topbar no color show
![image](https://user-images.githubusercontent.com/10168476/32686686-a25c6ba8-c66f-11e7-8bd8-6a5969b5c785.png)

# environment 
Quasar:  13.4
OS: 
Node: 7.10.0
NPM: 4.2.0
Browsers:
iOS: 11.0
Android:

**Comment by rstoenescu** [comment]
Will investigate. Seems quite odd. Maybe some quirks of ios 11 in particular.

**Comment by lenvonsam** [comment]
Expect to fix this bug @rstoenescu

**Comment by pdanpdan** [comment]
https://github.com/ionic-team/ionic/issues/12958

**Comment by rstoenescu** [comment]
Related: https://github.com/ionic-team/ionic/issues/12958

**Comment by rstoenescu** [comment]
Putting a self note for fixing this: https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator

**Comment by lenvonsam** [comment]
@rstoenescu  i have try the methods above without usefulness.

**Comment by lenvonsam** [comment]
@rstoenescu any progress?

**Comment by lenvonsam** [comment]
i fixed this problem @rstoenescu 
should add one block code in quasar framework ios css, modify below:
``` css
body.cordova.platform-ios .layout-header > .q-toolbar:first-child,
body.demo-site.within-iframe .layout-header > .q-toolbar:first-child,
body.cordova.platform-ios .layout-aside.top-padding,
body.demo-site.within-iframe .layout-aside.top-padding {
    /* Status bar height on iOS 11.0 */
  padding-top: constant(safe-area-inset-top);

  /* Status bar height on iOS 11+ */
  padding-top: env(safe-area-inset-top);
}
```
