### ISSUE TITLE
Selection column does not generate data-v- when using scoped style

### ISSUE THREAD

**Issue by adarshmadrecha** [quasarframework/quasar#11398]
**Describe the bug**
Selection column does not generate `data-v-264xyxyx` when using `scoped` style
https://codesandbox.io/s/busy-germain-h2749 

**To Reproduce**
Steps to reproduce the behaviour:
1. In table add `selection="multiple"`
2. Add Scoped Style
```css
<style lang="scss" scoped>
.q-table {
  // To format Table Heading
  tr:first-child {
    th {
      background: gray !important;
    }
  }
}
</style>
```
3. Check Element Pane in Dev Tools.

**Expected behaviour**
When adding `selection="multiple"` on the Table, it generates new table column. But this column does not contain `data-v-264xyxyx`. Because of this, its not possible to style the `td` and `th` when using `scoped` style. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11911938/142453198-c280d316-e308-45d9-b35e-f5ea17631799.png)

**Platform (please complete the following information):**
Quasar Version: 2.3.2
@quasar/app Version: 
@quasar/vite-plugin Version: 1.0.2

Quasar mode:
  - [x] SPA
  
Tested on:
  - [x] SPA

OS: Windows 10
Node: 16.3.x
NPM: 8.1.x
Browsers: Chrome 96.x

**Additional context**
