### ISSUE TITLE
Provide and example in documentation on change background-color of a disabled button ( or any component )?

### ISSUE THREAD

**Issue by jarrodhroberson** [quasarframework/quasar#13502]
### Description

I want to change `disabled q-btn` from just being `opacity: .6 !important` to have a different background color, in my case `gray`.

I found the following in `core/visibility.sass` 

```
.disabled, [disabled]
  opacity: .6 !important
```

I tried adding the following to my `app.scss` but it does not seem to affect anything.
The color does not change and opacity does not change either.

```
.disabled,
[disabled] {
  background-color: gray;
  opacity: .1;
}
```

**Can someone document the proper way to change the `background-color` of a `q-btn` when it is `disabled`?**

### Documentation Section URL

https://quasar.dev/vue-components/button#disable

### Areas

Components (quasar)

**Comment by sebaguse** [comment]
this worked for me in `app.scss`:
```css
  .q-btn.disabled {
    background: $grey-20 !important;
    color: $grey-40 !important;
    opacity: 1 !important;
  }
```
