### ISSUE TITLE
[15.1] Popover from Select shows briefly while the control first loads

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#1622]
It's pretty annoying, especially if you have many select controls.

![bug](https://user-images.githubusercontent.com/10562635/36588672-1a6b8852-1889-11e8-9129-08266174accf.PNG)

(the alert is there to capture the phenomenon)

I "fixed it" in my code using:
```css
.q-select .q-popover {
  display: none;
}
```
I don't know if there's any side-effects using this, though.
