### ISSUE TITLE
[Request] css helper: cursor grab

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#1817]
Support for a CSS helper to have a drag cursor could look like this:
```css
.cursor-grab {
    cursor: move; /* fallback: no `url()` support or images disabled */
    cursor: url(images/grab.cur); /* fallback: Internet Explorer */
    cursor: -webkit-grab; /* Chrome 1-21, Safari 4+ */
    cursor:    -moz-grab; /* Firefox 1.5-26 */
    cursor:         grab; /* W3C standards syntax, should come least */
}
.cursor-grab:active, .cursor-grabbing {
    cursor: url(images/grabbing.cur);
    cursor: -webkit-grabbing;
    cursor:    -moz-grabbing;
    cursor:         grabbing;
}
```
