### ISSUE TITLE
Add pointer div to QTooltip/QPopover

### ISSUE THREAD

**Issue by darkscript** [quasarframework/quasar#2105]
### Software version

Quasar: 0.16.0
OS: 
Node: 8.9.0
NPM: 5.6.0
Browsers: Mozilla and Chrome 
iOS:
Android: 7.1.1
Any other software related to your bug: No

### JsFiddle (for Quasar v0.15+ only)

Its more of an enhancement, not a bug

### What did you get as the error?
No errors, more of an improvement

### More Description
It would be great if q-tooltip has a pointer div like the one in this image below
![tootltip](https://user-images.githubusercontent.com/13992858/40768043-d225f052-64bc-11e8-9b1d-6bea0a29ecfb.png)
![tootltip2](https://user-images.githubusercontent.com/13992858/40768146-241d72c2-64bd-11e8-9803-3801a151ee12.png)

and even better, create a tooltip similar to google maps one like shown on this video I uploaded https://youtu.be/H__RjiS-5As

**Comment by nothingismagick** [comment]
I like this idea, but really need you to bear with us on this kind of feature request. Unless someone makes a well-thought out PR, I don't see this landing before 1.0

**Comment by darkscript** [comment]
@nothingismagick did add some more info, not sure if there is any more entry relevant to this issue/enhancement.

**Comment by rstoenescu** [comment]
Merging this with https://github.com/quasarframework/quasar/issues/2104.

**Comment by sonygod** [comment]
https://akryum.github.io/v-tooltip/

such like some features here? with direction arrow.

**Comment by rstoenescu** [comment]
Hi,

Sorry but closing this as no progress can be made. If you find Akryum's tooltip to be better suited for you, please use that.

**Comment by emahuni** [comment]
Is this going to be made? can we have the code so we can continue with it please?

**Comment by cdnrg-rt** [comment]
I know this is super old but I just had to do this and you can easily add a content-class prop and use css
example **<q-tooltip content-class="arrow-up"**

and use CSS (stylus in example)

.arrow-up
  overflow-y visible !important

  &:before  
    content ' '  
    width 0  
    height 0  
    border-left 20px solid transparent  
    border-right 20px solid transparent  
    border-bottom 20px solid $charcoalten  
    left 50%  
    margin-left -10px  
    position absolute  
    top -12px

**Comment by Shinigami92** [comment]
@cdnrg-rt There is no `content-class` anymore
Do you have a new working example?
I need an arrow-left

**Comment by TheSwordBreaker** [comment]
hello any update or find answer

**Comment by imlinhanchao** [comment]
> @cdnrg-rt There is no anymore Do you have a new working example? I need an arrow-left`content-class`

I resolve it. I was use Quasar 2. Use Scss :
```css

.q-tooltip--style {
  overflow-x: visible;
  overflow-y: visible;
  &::before {
    content: " ";
    width: 0;
    height: 0;
    border-top: 5px solid transparent;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-bottom: 5px solid transparent;
    position: absolute;
  }
  &.arrow-top::before {
    border-bottom-color: $tooltip-background;
    left: 50%;
    top: -10px;
    margin-left: -5px;
  }
  &.arrow-left::before {
    border-right-color: $tooltip-background;
    top: 50%;
    left: -10px;
    margin-top: -5px;
  }
  &.arrow-right::before {
    border-left-color: $tooltip-background;
    top: 50%;
    right: -10px;
    margin-top: -5px;
  }
  &.arrow-bottom::before {
    border-top-color: $tooltip-background;
    left: 50%;
    bottom: -10px;
    margin-left: -5px;
  }
}
```
And use component in vue like this:

```html
<q-tooltip anchor="center right" self="center left" class="arrow-left">
    something
</q-tooltip>
```
