### ISSUE TITLE
Combine quasar css helpers with custom classes using stylus

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#2131]
Is there a way to use stylus [extend](http://stylus-lang.com/docs/extend.html) to combine quasar css helpers with custom classes?

Like so:
```css
.my-custom-class {
  @extend .uppercase, .text-primary;

  opacity: 0.7;
}
```
