### ISSUE TITLE
Icons inside buttons use suboptimal font size

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#2134]
```css
.q-btn .q-icon, .q-btn .q-spinner {
    font-size: 1.4em;
}
```

Using the default font-size of 1em = 16px, the icon would be 22.4px. Material icons [should be displayed](https://github.com/google/material-design-icons/issues/648) at a certain (24px) optimal size.

There could be other types of icons that are sized suboptimally.
