### ISSUE TITLE
Feature Request: Disable Hover on timeline component

### ISSUE THREAD

**Issue by Boid-John** [quasarframework/quasar#2205]
Using Quasar 0.16 

When the user hovers over the dot of a timeline entry, there is some default css transition that happens. It's unintuitive for non-interactive components to have hover css. Could we have an option to disable this, or could someone explain which css class is responsible for a manual override. 

![image](https://user-images.githubusercontent.com/30223943/41816751-7af0c71e-7752-11e8-8f96-fe4b55cdb15a.png)

Thanks.

**Comment by shwilliam** [comment]
I don't believe there is a quick way to disable this default styling. However, the timeline-entry dot styles should be able to be overridden using the following CSS:
```css
.q-timeline-entry:hover .q-timeline-dot:before {
  background: [...];
  border: [...];
}
/* if using an icon */
.q-timeline-entry:hover .q-timeline-entry-with-icon:hover .q-timeline-dot .q-icon {
  color: [...];
}
```
