### ISSUE TITLE
[V1] [Feature Request] auto adjust carousel height to inner component

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/quasar#3761]
The current carousel usually crop images of a certain height. It would be good to have a prop that enables the carousel to auto adjust its height based on the image (or content) height.
I come from using vuetify and I am slowly transitioning my website to quasar. On Vuetify, I used the v-window to achieve the desired result. I use it to show different images with text to the users and having them cropped make understanding the images difficult.

**Comment by diegomagikal** [comment]
I need this, too. Besides, I think that the ratio control for QCarouselSlide (like QImg) would be a good idea.

**Comment by sskwrl** [comment]
You can view uncropped images by adding a variation of this css class to each slide

```css
.uncropped-image {
  background-size: contain;  /* don't crop the image  */
  background-repeat: no-repeat;  /* only show the image one time  */
  background-color: grey;  /* color to fill empty space with  */
}
```
