### ISSUE TITLE
[V1 - Feature request] Add option for centered text on QSeparator

### ISSUE THREAD

**Issue by VIM-Arcange** [quasarframework/quasar#4220]
It would nice to have options to add centered text on top of the the <hr> tag generated by the QSeparator

HTML/CSS sample code can be found here:
- for horizontal separator: https://codepen.io/scottzirkel/pen/yNxNME
- for vertical separator: https://codepen.io/Ruskyj/pen/voLsr

The color of the text should match the color of the separator or be defined via props.

**Comment by rstoenescu** [comment]
Hi,

This is pretty custom and introduces a lot of issues like changing the background color (which can be anything, even an image) and then seeing the resulting mess :) Also, we'd need to introduce a lot of props (text size etc etc) and at the end of the day we'll be making a very used component be 50 times slower to render :(

However, a component using that technique can be created in devland. You'll know exactly how to match the background.

**Comment by tohagan** [comment]
Went hunting for this feature today and I agree that the codepen examples above are a bit heavy weight BUT I found a _much simpler_ solution that would easily support a text label **slot** (so no need for text related props and much more flexible - label can include icons etc.) 

`border-bottom: 4px double #CCCCCC;` can be anything of course. This is just what I wanted for current project.

https://jsfiddle.net/qdpz43ku/12/



```html
    <div class="separator">Next section</div>
```

```css
.separator {
    display: flex;
    align-items: center;
    text-align: center;
}
.separator::before, .separator::after {
    content: '';
    flex: 1;
    border-bottom: 4px double #CCCCCC;
}
.separator::before {
    margin-right: .25em;
}
.separator::after {
    margin-left: .25em;
}
```
