### ISSUE TITLE
border-radius issue in QButtonGroup with QSeparator[vertical] + QBtn

### ISSUE THREAD

**Issue by luozhihua** [quasarframework/quasar#4947]
**Describe the bug**
border-radius issue in button-group q-separator vertical+q-btn

**Codepen (required)**
https://codepen.io/colinluo/pen/VwZPLVV

**Screenshots**
![image](https://user-images.githubusercontent.com/3764249/63521503-2533e600-c529-11e9-8526-8697996f19e6.png)

**How to fix**
Add following css code can fixed this issues. 
```css
.q-btn-group>.q-separator--vertical+.q-btn-item {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
} 
```

**Platform (please complete the following information):**
OS: MacOS Catalina 10.15 Beta
Node: v12.8.0
Browsers: Google Chrome  v78.0.3887.7 dev
