### ISSUE TITLE
"rtl:ignore" comment is ignored when using RTL and SASS

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#5828]
When using SASS and with RTL enabled. the following class should be left intact:

``` css
.my-class{
  text-align: left; /* rtl:ignore */
}
```
But it gets converted by postcss anyway. This problem does not happen when using Stylus.

tests on:
```
Pkg quasar........ v1.5.5
Pkg @quasar/app... v1.3.3
```
