### ISSUE TITLE
Font Awesome Duotone shifts

### ISSUE THREAD

**Issue by TheSinding** [quasarframework/quasar#6139]
**Describe the bug**
Some of Font Awesome Duotone icons are shifted.
It's fixed by adding the same CSS from "q-icon:before" to "q-icons:after" eg.
``` css
.q-icon:before, .q-icon:after {
    width: 100%;
    height: 100%;
    display: flex !important;
    align-items: center;
    justify-content: center;
}
```
**To Reproduce**
1. Use Font Awesome Duotone icons

**Expected behavior**
They should look like the ones on the font awesome webpage

**Screenshots**
How it looks
![image](https://user-images.githubusercontent.com/5576291/72601732-4224e780-3916-11ea-83be-72329c10b534.png)

How it should look
![image](https://user-images.githubusercontent.com/5576291/72601783-5b2d9880-3916-11ea-81d8-eeaaef9b212b.png)
