### ISSUE TITLE
Notify Plugin: Enhanced progress bar

### ISSUE THREAD

**Issue by matthiasmeier** [quasarframework/quasar#6422]
As the "progress" bar is an indicator of how long a notification will be visible, I think it’d be more intuitive to show the remaining time instead of the amount of time that’s already passed.

Also, it’d be great if there was an option to choose the size of the progress bar as it is very prominent using the full height of the notification. In addition, the color of the progress bar should either be set automatically to light or dark (white / black) depending on the color of the notification (or an additional option like `progressColor` could be added).

**Describe the solution you'd like**
I’d like to be able to not only set the `progress` to `true` or `false`, but also set it to `reverse` (or something similar).

```javascript
this.$q.notify({
    message: 'Jim emailed you.',
    progress: 'reverse' // true | false | 'reverse'
})
```

Alternatively, Quasar might also change the behaviour a bit and accept e.g. `normal ` and `reverse` as strings and otherwise don’t show the progress bar.

**Describe alternatives you've considered**
This can easily be achieved by adding some CSS – or a progressClass and CSS (we already use this in our project):

```scss
// Progress bar
// Only show a little progress bar at the bottom of the notification.
.q-notification__progress {
    top: auto;
    height: 3px;
    opacity: 0.15;

    // Optionally use a dark progress bar on light color notifications
    &--dark {
        background-color: black;
    }
}
// As the "progress" bar is an indicator of how long a notification will be visible, it’d be more intuitive to show the
// remaining time instead of the amount of time that’s already passed.
@keyframes q-notif-progress {
    0% { width: 100%; }
    100% { width: 0%; }
}
```

**Examples**
<img width="1342" alt="Screenshot 2020-02-19 at 11 45 16" src="https://user-images.githubusercontent.com/900640/74828914-3c089900-5310-11ea-9d55-64bde70f49c5.png">
