### ISSUE TITLE
Misplaced space for the home bar in iOS

### ISSUE THREAD

**Issue by louisameline** [quasarframework/quasar#6696]
Hello,

When using the bottom sheet on iOS with Cordova, the white space which is meant to accomodate the home bar is below the bottom sheet (see screenshot), while I would expect it to be inside the bottom sheet. Same thing for maximized dialogs and such: it doesn't look good.

I'd like an easy way to disable Quasar's built in paddings and manage them on my own.
It's not ideal to have to have to override things like:
```css
  body.q-ios-padding .q-dialog__inner > div {
    max-height: calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom)) !important;
  }
}
```

Also, FYI the doc says that qHeader, qFooter and thenotifications have the notch/home bar support built in. I see that in the header, but not the footer.

Thank you

![thumbnail2](https://user-images.githubusercontent.com/371814/77786680-7e836b00-705e-11ea-9d3c-42ee44e63c04.jpg)
