### ISSUE TITLE
FOUDT: Flash of Unstyled Dark Theme

### ISSUE THREAD

**Issue by Grawl** [quasarframework/quasar#7530]
**Describe the bug**

[FOUDT: Flash of Unstyled Dark Theme](https://webcloud.se/blog/2020-04-06-flash-of-unstyled-dark-theme/)

**Codepen/jsFiddle/Codesandbox**: https://codesandbox.io/s/peaceful-spence-jmu5d

**To Reproduce**
Steps to reproduce the behavior using given sandbox:
1. Make sure your browser is supporting `(prefers-color-scheme: dark)` media query and turn it on
2. Go to sandbox with link given above
3. Wait until sandbox will be ready
4. See app is rendered in light theme as initial state
5. See app becoming dark after you see app in light theme

**Expected behavior**
App is rendered in dark theme as initial render

**Platform (please complete the following information):**
OS: macOS Catalina 10.15.5 (19F101)
Node: >= 10.17.0
NPM: >= 6.13.4
Yarn: >= 1.19.1
Browsers: Chrome 84.0.4147.89, Safari 13.1.1 (15609.2.9.1.2)

**Comment by Grawl** [comment]
I faced this issue because dark theme in Quasar is made using JS. In SSR mode, CSS and HTML are rendered before JS is loaded.

A way to solve this issue is to use `(prefers-color-scheme: dark)` instead (or with) CSS classes.

So, instead of this:

```css
body.body--dark {
    color: white;
    background: hsl(0deg 0% 7%);
}
```

It should be this:

```css
@media (prefers-color-scheme: dark) {
body {
    color: white;
    background: hsl(0deg 0% 7%);
}
}
```

To add dark theme toggle, [`postcss-dark-theme-class`](https://github.com/postcss/postcss-dark-theme-class) can be used.
