### ISSUE TITLE
color helper classes via a toupellist

### ISSUE THREAD

**Issue by relaxdays-bewerbung** [quasarframework/quasar#7607]
**Is your feature request related to a problem? Please describe.**
We have a wide variant of gray colors in our apps, so overwriting the 10 grey variables from quasar sass variables is not enough.
So we need to define the helperclasses ourselves.

**Describe the solution you'd like**
If we had a color variable list like we have for spaces, we could just overwrite that variable and get all the color helperclasses we need.

**Describe alternatives you've considered**
We have created an own set helpeclasses that match the quasar syntax, but it's messy.

This feature would give us a lot of comfort.

**Comment by relaxdays-bewerbung** [comment]
Our current soultion:
```scss
$colors: (
  grey-97: $grey-97,
  grey-83: $grey-83,
  grey-80: $grey-80,
  grey-71: $grey-71,
  grey-60: $grey-60,
  grey-55: $grey-55,
  grey-49: $grey-49,
  grey-39: $grey-39,
  grey-31: $grey-31
  grey-22: $grey-22,
  grey-12: $grey-12,,
);

@each $name, $color in $colors {
  .text-#{$name} {
    color: $color !important;
  }

  .bg-#{$name} {
    background-color: $color !important;
  }
}
```
