### ISSUE TITLE
native css color variables causes problems in embedded quasar app

### ISSUE THREAD

**Issue by luckylooke** [quasarframework/quasar#7936]
Hello, thank you for sharing!

**Describe the bug**
We have built Quasar web app which is embedding to different webs, since quasar classes conflicts with parent web I had to encapsulate it:
```css
.wsk-root {
  @import './wsk_vars.scss';
  @import './wsk_theme.scss';
  @import '~quasar/src/css';
  @import '~quasar/src/css/flex-addon';
}
```
Since you have following in your sources
```css
:root
  --q-color-primary:      $primary
  --q-color-secondary:    $secondary
  --q-color-accent:       $accent
  --q-color-positive:     $positive
  --q-color-negative:     $negative
  --q-color-info:         $info
  --q-color-warning:      $warning
  --q-color-dark:         $dark
```
it results into:
```css
.wsk-root :root {
  --q-color-primary: #1083ff;
  --q-color-secondary: #d4d7d9;
  --q-color-accent: #fc464a;
  --q-color-positive: #80c700;
  --q-color-negative: #dd5656;
  --q-color-info: #1083ff;
  --q-color-warning: #eeae12;
  --q-color-dark: #1d1d1d;
}
```
then I use in some components attribute `color="secondary"` and it does not apply
```css
.wsk-root .bg-secondary {
    background: var(--q-color-secondary) !important;
}
```

**Expected behavior**
Using preprocessor variables would fix this and allow quasar styles to by properly embedded

Thank you 🙏
