### ISSUE TITLE
SSR dev mode js and fonts path bug

### ISSUE THREAD

**Issue by nevadavid** [quasarframework/quasar#8062]
When I run my project on SSR dev mode, the vendor, app js and fonts get an slash (/) begin character.

```js
<script src="/js/vendor.js" defer></script>
<script src="/js/app.js" defer></script>
```

```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 100;
  src: url(/fonts/KFOkCnqEu92Fr1MmgVxIIzQ.woff) format('woff');
}
```

I use my app in docker container and my folder stucture is: .../quasarssr/account (in docker).
In this case it will cause error when the browser try to load js files, because these paths will be absolute paths.
In SPA dev mode doesn't appear slash character, so that is good.

Can I modify these files paths? (For example in quasar.conf.js)

**Quasar:** v1.14.3
**Quasar/app:** v2.1.6
**Dev mode:** ssr
