### ISSUE TITLE
[RTL][SCSS] rtl:ignore is not respected during `quasar build`

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#8162]
When using `scss` or `sass` using the special syntax of ` #{"/* rtl:ignore */"};` for signaling the `rtlcss` to ignore this rule during build process, will not do anything and the direction will be flipped anyway.

Since #8073 these `rtl:ignore` rules are used in core positioning classes and this issue causes a RTL Quasar project to be pretty much unusable with current version because everything for example `QHeader` will have positioning problem and won't stretch to the whole width of screen.

Steps to reproduce on a freshly created Quasar` v1.14.7` project:
1. set `lang: 'fa-ir'` and `rtl:true` in `quasar.conf.js`
2. `quasar build && cd dist/spa && quasar serve`
3. try closing the drawer and see the header will shrink to its content width.

This does not happen during development using `quasar dev` and happens only with `quasar build` which makes this a very tricky issue because the problem won't be seen until the project is deployed and everything during development looks fine.

**Comment by Saeid-Za** [comment]
Hello, I can reproduce this issue by following the steps, here's some additional info on the problem:
related CSS at the dev mode : 
```css
.fixed-top {
    top: 0;
    left: 0 /* rtl:ignore */;
    right: 0 /* rtl:ignore */;
}
```
and CSS at prod mode :
```css
.fixed-top{top:0;left:0}
[dir=ltr] .fixed-top{right:0}
[dir=rtl] .fixed-top{left:0}
```
as we can see, the transformation process, was not ignored for these two line of CSS at prod mode, and there is no `ignore` comment in prod mode (stripped away by compilation process).
