### ISSUE TITLE
Make QCard whole clickable or in different QCard sections

### ISSUE THREAD

**Issue by thewebartisan7** [quasarframework/quasar#8709]
The problem: make `q-card` whole clickable for example when is a post, or only in certain `q-card-section` .
Right now the style of content inherit style of link, see screenshot:

<img width="827" alt="Screenshot 2021-03-26 at 05 13 09" src="https://user-images.githubusercontent.com/57477934/112854966-a876cf80-90ae-11eb-9730-a09b07f50f2d.png">

Possible solution: add a class helper like:

```css
.stretched-link::after {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1;
  content: "";
}
```

Then we can:

```html
    <div class="relative-position">
      <q-card-section>
        <div class="text-h6">{{ post.title }}</div>
        <div class="text-subtitle2">
          {{ post.published_at }} — {{ post.read_time }}
        </div>
      </q-card-section>
      <q-card-section class="q-pt-none">
        {{ post.summary }}
      </q-card-section>
      <router-link
        :to="{ name: 'show-post', params: { slug: post.slug } }"
        class="stretched-link"
      ></router-link>
    </div>
```
