### ISSUE TITLE
q-input >textarea< resize button badly placed (Qv1 & Qv2)

### ISSUE THREAD

**Issue by RejDev** [quasarframework/quasar#8888]
Hello,

**Describe the bug**
**Textarea**'s resize button **is shifted to the left**, same problem on the examples in the documentation
https://quasar.dev/vue-components/input#textarea

the culprit is this class css :

```css
.q-field--filled .q-field__control {
    padding: 0 12px;
    background: rgba(0,0,0,0.05);
    border-radius: 4px 4px 0 0;
}
```
especially this part
  padding: 0 **12px;**
to correct this, just make the :
  padding: 0 **0**  or   padding: 0 **2px**  

**Platform (please complete the following information):**
Quasar Version: v1.15.10  And  v2.0.0-beta.12

Quasar mode:
  - [ X] SPA

Tested on:
  - [X ] SPA

OS: Manjaro
Browsers: Firefox And Chromium

Thank you in advance..
